name: test
on: [pull_request]

env:
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: sudo bash tools/install-tools.sh
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert and push images
        run: |
          crane copy --platform=linux/amd64 alpine:3.15.3 ghcr.io/stargz-containers/alpine:test
